export function rub(n: number) {
  return new Intl.NumberFormat("ru-RU").format(n) + " ₽";
}

export function num(n: number) {
  return String(n).replace(".", ",");
}

export function phoneHref(phone: string) {
  return "tel:+" + phone.replace(/\D/g, "").replace(/^8/, "7");
}

export function whatsappHref(number: string, text?: string) {
  const digits = number.replace(/\D/g, "");
  return `https://wa.me/${digits}${text ? `?text=${encodeURIComponent(text)}` : ""}`;
}

export function routeHref(lat: string, lon: string) {
  return `https://yandex.ru/maps/?rtext=~${lat},${lon}&rtt=auto`;
}

export function mapHref(lat: string, lon: string) {
  return `https://yandex.ru/maps/?pt=${lon},${lat}&z=17&l=map`;
}

export function productTitle(p: { name: string; diameter: number; width: number; pcd: string; et: number }) {
  return `${p.name} R${p.diameter} ${num(p.width)}J ${p.pcd} ET${num(p.et)}`;
}

/** Small thumbnail variant generated by the importer (/catalog/x.webp → /catalog/x-sm.webp). */
export function thumb(url: string) {
  return url.startsWith("/catalog/") ? url.replace(/\.webp$/, "-sm.webp") : url;
}

export function makesList(s: string) {
  return s
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean);
}

export const LEAD_STATUSES = [
  { value: "NEW", label: "Новая", tone: "gold" },
  { value: "IN_WORK", label: "В работе", tone: "blue" },
  { value: "CONTACTED", label: "Связались", tone: "violet" },
  { value: "DONE", label: "Завершена", tone: "green" },
] as const;

export const LEAD_TYPES: Record<string, string> = {
  podbor: "Подбор дисков",
  product: "Заявка на товар",
  callback: "Обратный звонок",
};

export function plural(n: number, one: string, few: string, many: string) {
  const a = Math.abs(n) % 100;
  const b = a % 10;
  if (a > 10 && a < 20) return many;
  if (b > 1 && b < 5) return few;
  if (b === 1) return one;
  return many;
}
