/**
 * Seeds the database:
 *  - catalogue from data/products.json (generated by scripts/import_xls.py)
 *  - default site settings, demo reviews, FAQ
 *  - admin account from ADMIN_LOGIN / ADMIN_PASSWORD (bcrypt hash only)
 *
 * Existing products are matched by SKU and left untouched (so admin edits, e.g. prices,
 * survive a re-seed). Pass --reset-catalog to wipe and re-import products.
 */
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { readFileSync } from "node:fs";
import path from "node:path";
import { SETTINGS_DEFAULTS } from "../src/lib/settings-defaults";

const prisma = new PrismaClient();

type ImportedProduct = {
  sku: string;
  slug: string;
  name: string;
  model: string;
  brand: string;
  diameter: number;
  width: number;
  pcd: string;
  et: number;
  dia: number;
  finish: string;
  finishCode: string;
  type: string;
  axle: string | null;
  compatibleMakes: string[];
  stockQty: number;
  warehouse: string;
  price: number;
  images: string[];
  description?: string;
};

const REVIEWS = [
  { author: "Алексей (пример)", car: "BMW X5 G05", text: "Демо-отзыв. Подобрали диски R21 по VIN за 15 минут, привезли на следующий день прямо к шиномонтажу.", sort: 1 },
  { author: "Марина (пример)", car: "Kia Sportage", text: "Демо-отзыв. Хотела чёрные диски с полировкой — показали несколько вариантов в наличии, помогли с вылетом.", sort: 2 },
  { author: "Дмитрий (пример)", car: "Mercedes-Benz E-Class", text: "Демо-отзыв. Отличное качество покраски, всё как на фото. Доставили в тот же день по Москве.", sort: 3 },
  { author: "Игорь (пример)", car: "Toyota Camry", text: "Демо-отзыв. Удобно, что можно всё обсудить в WhatsApp и сразу получить фото конкретного комплекта.", sort: 4 },
];

const FAQ = [
  { q: "Как подобрать диски под мой автомобиль?", a: "Оставьте заявку с маркой, моделью и VIN — специалист Lendisk проверит разболтовку (PCD), вылет (ET), ширину и центральное отверстие (DIA) и предложит подходящие варианты из наличия." },
  { q: "Диски действительно в наличии?", a: "Да, в каталоге показаны позиции со склада. Перед оформлением менеджер подтвердит наличие и точное количество комплектов." },
  { q: "Сколько стоит доставка и как быстро привезёте?", a: "Доставляем по Москве и Московской области. Возможна доставка в день заказа или на следующий день — зависит от наличия, адреса и времени оформления. Стоимость менеджер назовёт при подтверждении заказа." },
  { q: "Цена указана за один диск или за комплект?", a: "Цена в каталоге указана за один диск. Стоимость комплекта из 4 дисков менеджер подтвердит при оформлении." },
  { q: "Можно ли посмотреть диски вживую?", a: "Да, приезжайте в магазин Lendisk в Лобне по адресу ул. Лейтенанта Бойко, 91А. Лучше заранее позвонить, чтобы мы подготовили нужные модели." },
  { q: "Что означают обозначения BMF, HB, MB?", a: "Это коды покрытия: BMF — чёрный с полированной лицевой частью, HB — Hyper Black (гипер-чёрный), MB — матовый чёрный, GMF — графит с полировкой, S — серебристый." },
];

/** Picks photogenic items per diameter, alternating brands so showcases look varied. */
function pickFeatured(items: ImportedProduct[], diameters: number[], perDiameter: number, offset: number, taken = new Set<string>()) {
  const out = new Set<string>();
  const usedBrands: string[] = [];
  for (const d of diameters) {
    const pool = items.filter((p) => p.diameter === d && p.images.length > 0 && p.stockQty >= 4 && !taken.has(p.sku));
    const byBrand = new Map<string, ImportedProduct[]>();
    for (const p of pool) byBrand.set(p.brand, [...(byBrand.get(p.brand) || []), p]);
    const brands = [...byBrand.keys()].sort((a, b) => usedBrands.filter((x) => x === a).length - usedBrands.filter((x) => x === b).length);
    let picked = 0;
    for (const b of brands) {
      const list = byBrand.get(b)!;
      const p = list[Math.min(offset, list.length - 1)];
      if (!p || out.has(p.sku)) continue;
      out.add(p.sku);
      usedBrands.push(b);
      if (++picked >= perDiameter) break;
    }
  }
  return out;
}

async function main() {
  const reset = process.argv.includes("--reset-catalog");
  const file = path.join(process.cwd(), "data", "products.json");
  const items: ImportedProduct[] = JSON.parse(readFileSync(file, "utf8"));

  if (reset) {
    await prisma.productImage.deleteMany();
    await prisma.product.deleteMany();
  }

  const popular = pickFeatured(items, [18, 19, 20, 21], 2, 0);
  const fresh = pickFeatured(items, [17, 19, 20, 22], 2, 3, popular);

  const existing = new Set((await prisma.product.findMany({ select: { sku: true } })).map((p) => p.sku));
  let created = 0;
  for (const it of items) {
    if (existing.has(it.sku)) continue;
    await prisma.product.create({
      data: {
        sku: it.sku,
        slug: it.slug,
        name: it.name,
        model: it.model,
        brand: it.brand,
        diameter: it.diameter,
        width: it.width,
        pcd: it.pcd,
        et: it.et,
        dia: it.dia,
        finish: it.finish,
        finishCode: it.finishCode,
        type: it.type,
        axle: it.axle,
        compatibleMakes: it.compatibleMakes.join(", "),
        price: it.price,
        stockQty: it.stockQty,
        inStock: it.stockQty > 0,
        warehouse: it.warehouse,
        description: it.description || "",
        isPopular: popular.has(it.sku),
        isNew: fresh.has(it.sku),
        images: { create: it.images.map((url, i) => ({ url, sort: i })) },
      },
    });
    created++;
  }
  console.log(`Products: ${created} created, ${existing.size} kept`);

  for (const [key, value] of Object.entries(SETTINGS_DEFAULTS)) {
    await prisma.setting.upsert({ where: { key }, update: {}, create: { key, value } });
  }

  if ((await prisma.review.count()) === 0) {
    await prisma.review.createMany({ data: REVIEWS.map((r) => ({ ...r, rating: 5, isDemo: true })) });
  }
  if ((await prisma.faqItem.count()) === 0) {
    await prisma.faqItem.createMany({ data: FAQ.map((f, i) => ({ question: f.q, answer: f.a, sort: i })) });
  }

  const login = process.env.ADMIN_LOGIN;
  const password = process.env.ADMIN_PASSWORD;
  if (login && password) {
    // The password from env is applied only when the account is created (or ADMIN_RESET_PASSWORD=1),
    // so a password changed in the admin panel survives re-seeding on every deploy.
    const exists = await prisma.adminUser.findUnique({ where: { login } });
    if (!exists || process.env.ADMIN_RESET_PASSWORD === "1") {
      const passwordHash = await bcrypt.hash(password, 12);
      await prisma.adminUser.upsert({ where: { login }, update: { passwordHash }, create: { login, passwordHash } });
      console.log(`Admin account "${login}" ${exists ? "password reset" : "created"}`);
    } else {
      console.log(`Admin account "${login}" already exists — password unchanged`);
    }
  } else {
    console.warn("ADMIN_LOGIN / ADMIN_PASSWORD not set — admin account not created");
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
